feat: add Asai_compile.MarkedText
RedPRL/asai pull request #15
Opened 2022-08-05 15:04 UTC by favonia

Implement the compiler

2022-08-08 20:33 UTC, favonia commented
Blocked by #16.

2022-08-09 19:42 UTC, favonia commented
I can update this PR after #17.

2022-08-09 21:05 UTC, TOTBWF requested changes

2022-08-09 22:21 UTC, favonia commented on src/file/Marker.ml
> +    if i < eof && R.unsafe_get pos.file_path i = '\n' then
Fixed.

2022-08-09 22:21 UTC, favonia commented on src/file/Asai_file.ml
> +  val format : splitting_threshold:int -> Code.t Asai.Diagnostic.t -> Code.t Marked.t
Update: use `assemble`

2022-08-09 22:27 UTC, merged